categories:
  bots:
    display: true
    pagename: Discord Botlist
    shortname: Bots
    add: Add your own bot
    invite: Add this bot
    parallax: /assets/images/background_bots.jpg
    description: The botlist with built-in GitHub integration
    path: /
    contribute: /docs/adding-a-bot
  servers:
    display: true
    pagename: Discord Serverlist
    shortname: Servers
    add: Add your own server
    invite: Join this server
    parallax: /assets/images/background_servers.jpg
    description: The server list with built-in GitHub integration
    path: /servers
    contribute: https://github.com/Terminal/Discord_Fork/blob/master/README.md
  bans:
    display: false
    pagename: Discord Banlist
    shortname: Bans
    add: Report a user
    parallax: /assets/images/background_hongkong.jpg
    description: The list you fork to throw your hammer.
    path: /bans
    contribute: https://github.com/Terminal/Discord_Fork/blob/master/README.md
  docs:
    display: true
    pagename: Discord Fork Documentation
    shortname: Documentation
    add: View source code on GitHub
    parallax: /assets/images/background_bots.jpg
    description: It's because nobody knows what they're doing
    path: /docs
    contribute: https://github.com/terminal/discord_fork
